spring.application.name=payroll-service

server.port=8083
spring.data.mongodb.uri=mongodb://localhost:27017/payroll_db
jwt.secret=YourVeryLongSecretKeyThatMustBeAtLeast32CharactersLong123456
jwt.expiration=86400000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packagesToScan=com.ibm.payroll

employee-service.base-url=http://localhost:8082
auth-service.base-url=http://localhost:8081
